name: Lint and Fix C# Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: |
        cd csharp-linting-example
        dotnet restore

    - name: Build Project
      run: dotnet build --no-restore

    - name: Run StyleCop Analyzers
      run: dotnet build --no-restore -p:StyleCopAnalyzersEnabled=true

    - name: Format Code
      run: dotnet format
